export const sdfCompletions = [
    {
      label: "sdf_sphere",
      type: "function",
      detail: "sdf_sphere(center=(0.5, 0.5, 0.5), radius=0.3)",
      info: "Signed distance field of a sphere.",
    },
    {
      label: "sdf_box",
      type: "function",
      detail: "sdf_box(bounds=(0.5, 0.5, 0.5), center=(0.5, 0.5, 0.5))",
      info: "SDF of an axis-aligned box.",
    },
    {
      label: "sdf_rounded_box",
      type: "function",
      detail: "sdf_rounded_box(bounds=(0.5, 0.5, 0.5), radius=0.1, center=(0.5, 0.5, 0.5))",
      info: "SDF of a box with rounded edges.",
    },
    {
      label: "sdf_box_frame",
      type: "function",
      detail: "sdf_box_frame(bounds, edge_thickness, center)",
      info: "SDF of a hollow box frame.",
    },
    {
      label: "sdf_torus",
      type: "function",
      detail: "sdf_torus(center, major_radius, minor_radius)",
      info: "SDF of a torus.",
    },
    {
      label: "sdf_capped_torus",
      type: "function",
      detail: "sdf_capped_torus(sc, ra, rb, center)",
      info: "SDF of a capped torus shape.",
    },
    {
      label: "sdf_link",
      type: "function",
      detail: "sdf_link(le, r1, r2, center)",
      info: "SDF of a link shape.",
    },
    {
      label: "sdf_cone_exact",
      type: "function",
      detail: "sdf_cone_exact(angle_sin_cos, height, center)",
      info: "Accurate SDF of a cone using projection.",
    },
    {
      label: "sdf_cone",
      type: "function",
      detail: "sdf_cone(c=(sinθ, cosθ), h=height, center)",
      info: "Simple cone SDF using dot product.",
    },
    {
      label: "gaussian_sphere",
      type: "function",
      detail: "gaussian_sphere(center, strength)",
      info: "Radial Gaussian field centered at a point.",
    },
    {
      label: "gaussian_cube",
      type: "function",
      detail: "gaussian_cube(center, scale)",
      info: "Gaussian falloff cube field.",
    },
    {
      label: "wave_pattern",
      type: "function",
      detail: "wave_pattern(freq)",
      info: "Sinusoidal wave field in 3D.",
    },
    {
      label: "gyroid",
      type: "function",
      detail: "gyroid(freq)",
      info: "Gyroid triply periodic minimal surface field.",
    },
    {
      label: "op_tx",
      type: "function",
      detail: "op_tx(transform_matrix, primitive_fn)",
      info: "Applies a transform to an SDF function.",
    },
    {
      label: "translate",
      type: "function",
      detail: "translate(tx, ty, tz)",
      info: "Creates a translation matrix.",
    },
    {
      label: "scale",
      type: "function",
      detail: "scale(sx, sy, sz)",
      info: "Creates a scaling matrix.",
    },
    {
      label: "rotate_x",
      type: "function",
      detail: "rotate_x(theta)",
      info: "Creates a rotation matrix around the X axis.",
    },
    {
      label: "rotate_y",
      type: "function",
      detail: "rotate_y(theta)",
      info: "Creates a rotation matrix around the Y axis.",
    },
    {
      label: "rotate_z",
      type: "function",
      detail: "rotate_z(theta)",
      info: "Creates a rotation matrix around the Z axis.",
    },
    {
      label: "combine",
      type: "function",
      detail: "combine(*matrices)",
      info: "Combines multiple transform matrices.",
    },
    {
      label: "smooth_step",
      type: "function",
      detail: "smooth_step(edge0, edge1, x)",
      info: "Smooth Hermite interpolation.",
    },
    {
      label: "clamp",
      type: "function",
      detail: "clamp(x, min_val, max_val)",
      info: "Clamps x between min_val and max_val.",
    },
    {
      label: "normalize_to_sdf_range",
      type: "function",
      detail: "normalize_to_sdf_range(field)",
      info: "Maps a scalar field to the range [-1, 1].",
    },
    {
      label: "union",
      type: "function",
      detail: "union(a, b)",
      info: "Takes the minimum of two fields.",
    },
    {
      label: "intersection",
      type: "function",
      detail: "intersection(a, b)",
      info: "Takes the maximum of two fields.",
    },
    {
      label: "difference",
      type: "function",
      detail: "difference(a, b)",
      info: "Subtracts one field from another.",
    },
    {
      label: "xor",
      type: "function",
      detail: "xor(a, b)",
      info: "Exclusive OR of two fields.",
    },
    {
      label: "smooth_union",
      type: "function",
      detail: "smooth_union(a, b, k)",
      info: "Soft blend between a and b.",
    },
    {
      label: "smooth_intersection",
      type: "function",
      detail: "smooth_intersection(a, b, k)",
      info: "Soft intersection between a and b.",
    },
    {
      label: "smooth_difference",
      type: "function",
      detail: "smooth_difference(a, b, k)",
      info: "Soft difference of b from a.",
    },
    {
      label: "lerp",
      type: "function",
      detail: "lerp(a, b, t)",
      info: "Linear interpolation between a and b.",
    },
    {
      label: "blend",
      type: "function",
      detail: "blend(a, b, mask)",
      info: "Blends a and b based on mask weight.",
    }
  ];